pipeline {
  agent {
    docker { image 'node:16-alpine' }
    args '-u root' // needed for installing packages
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
